apiVersion: apps/v1
kind: Deployment
metadata:
  name: faizal-nginx-deployment
  namespace: mfaizalbe-eks-activity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: faizal-nginx-service-account
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80